# Generated by Django 5.1 on 2024-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Login'),
            preserve_default=False,
        ),
    ]
