# Generated by Django 5.1 on 2024-09-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_user_email_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
    ]
