# Generated by Django 5.1.1 on 2024-10-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_user_bearer_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headmenu',
            options={'ordering': ['index'], 'verbose_name': 'пункт', 'verbose_name_plural': 'пункты'},
        ),
        migrations.AddField(
            model_name='headmenu',
            name='index',
            field=models.CharField(default='99', max_length=100, verbose_name='Порядковый номер пункта'),
        ),
    ]
