# Generated by Django 5.1.2 on 2024-11-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_mobile_printer_white',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выбранный мобильный принтер с белой бумагой'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_mobile_printer_yellow',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выбранный мобильный принтер с желтой бумагой'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_stationary_printer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выбранный стационарный принтер'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_thermo_printer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выбранный термопринтер'),
        ),
    ]
