# Generated by Django 5.1 on 2024-09-04 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 19, 58, 10, 948739, tzinfo=datetime.timezone.utc), verbose_name='Дата и время ошибки'),
        ),
    ]
