# Generated by Django 5.1.1 on 2024-10-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.CharField(max_length=100, verbose_name='PLU')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('quantity_in_basket', models.CharField(max_length=100, verbose_name='Количество в корзине')),
                ('stock_quantity', models.CharField(max_length=100, verbose_name='Остаток на момент добавление')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.basket')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
