# Generated by Django 5.1.1 on 2024-10-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0002_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='state',
            field=models.CharField(default='in_work', max_length=100, verbose_name='Состояние корзины'),
        ),
    ]
